In [45]:
import pandas as pd

In [46]:
# reading a csv file
df_exams = pd.read_csv('student_performance.csv')
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
0,1,Male,21,14,93,93,1,71,74,Pass,Bachelor's Degree
1,2,Female,21,21,94,69,1,95,79,Pass,Bachelor's Degree
2,3,Male,17,24,83,73,8,50,53,Pass,PhD
3,4,Male,19,28,52,99,4,59,74,Fail,PhD
4,5,Male,18,9,86,98,1,63,87,Pass,Bachelor's Degree

# 1 Create Index

In [47]:
import numpy as np
import random as rd

In [48]:
# creating non repetitive values for index
new_index = np.arange(0,500,1)

In [49]:
# shuffling the indexes
rd.shuffle(new_index)

In [50]:
# create a new column with new index
df_exams['New_Index'] = new_index
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education,New_Index
0,1,Male,21,14,93,93,1,71,74,Pass,Bachelor's Degree,406
1,2,Female,21,21,94,69,1,95,79,Pass,Bachelor's Degree,163
2,3,Male,17,24,83,73,8,50,53,Pass,PhD,97
3,4,Male,19,28,52,99,4,59,74,Fail,PhD,373
4,5,Male,18,9,86,98,1,63,87,Pass,Bachelor's Degree,10
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,PhD,223
496,497,Male,21,18,69,63,10,96,55,Pass,High School,174
497,498,Female,20,35,86,85,6,68,41,Fail,Master's Degree,86
498,499,Male,18,28,53,82,5,84,79,Fail,Associate Degree,385
499,500,Female,17,39,77,72,1,88,56,Pass,Associate Degree,84

# 2 Set Index

In [51]:
# set New_Index column as index
df_exams.set_index('New_Index', inplace = True)
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
New_Index,,,,,,,,,,,
406,1,Male,21,14,93,93,1,71,74,Pass,Bachelor's Degree
163,2,Female,21,21,94,69,1,95,79,Pass,Bachelor's Degree
97,3,Male,17,24,83,73,8,50,53,Pass,PhD
373,4,Male,19,28,52,99,4,59,74,Fail,PhD
10,5,Male,18,9,86,98,1,63,87,Pass,Bachelor's Degree
...,...,...,...,...,...,...,...,...,...,...,...
223,496,Male,21,21,73,83,0,40,77,Pass,PhD
174,497,Male,21,18,69,63,10,96,55,Pass,High School
86,498,Female,20,35,86,85,6,68,41,Fail,Master's Degree
385,499,Male,18,28,53,82,5,84,79,Fail,Associate Degree
84,500,Female,17,39,77,72,1,88,56,Pass,Associate Degree

# 3 Sort Index

In [56]:
# sort dataframe by New_Index
df_exams.sort_index()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
New_Index,,,,,,,,,,,
0,118,Female,20,15,87,91,5,72,78,Pass,High School
1,366,Male,20,15,57,54,5,99,65,Fail,Master's Degree
2,36,Male,20,16,88,63,3,92,60,Pass,Associate Degree
3,139,Male,20,9,64,99,1,99,94,Pass,Master's Degree
4,423,Female,22,33,93,88,8,42,89,Pass,Associate Degree
...,...,...,...,...,...,...,...,...,...,...,...
495,85,Male,18,12,53,77,1,90,69,Fail,Associate Degree
496,398,Female,22,10,59,98,4,67,46,Fail,Bachelor's Degree
497,354,Female,22,11,69,73,9,90,44,Fail,High School
498,370,Male,20,16,67,93,9,58,91,Pass,Bachelor's Degree
499,414,Male,19,11,51,86,0,50,42,Fail,Bachelor's Degree

In [58]:
# sort descending
df_exams.sort_index(ascending=False, inplace=True)
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
New_Index,,,,,,,,,,,
499,414,Male,19,11,51,86,0,50,42,Fail,Bachelor's Degree
498,370,Male,20,16,67,93,9,58,91,Pass,Bachelor's Degree
497,354,Female,22,11,69,73,9,90,44,Fail,High School
496,398,Female,22,10,59,98,4,67,46,Fail,Bachelor's Degree
495,85,Male,18,12,53,77,1,90,69,Fail,Associate Degree
...,...,...,...,...,...,...,...,...,...,...,...
4,423,Female,22,33,93,88,8,42,89,Pass,Associate Degree
3,139,Male,20,9,64,99,1,99,94,Pass,Master's Degree
2,36,Male,20,16,88,63,3,92,60,Pass,Associate Degree
1,366,Male,20,15,57,54,5,99,65,Fail,Master's Degree
0,118,Female,20,15,87,91,5,72,78,Pass,High School