In [19]:
import pandas as pd

In [20]:
# reading a csv file
df_exams = pd.read_csv('student_performance.csv')
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
0,1,Male,21,14,93,93,1,71,74,Pass,Bachelor's Degree
1,2,Female,21,21,94,69,1,95,79,Pass,Bachelor's Degree
2,3,Male,17,24,83,73,8,50,53,Pass,PhD
3,4,Male,19,28,52,99,4,59,74,Fail,PhD
4,5,Male,18,9,86,98,1,63,87,Pass,Bachelor's Degree

# 1 Rename Column

In [21]:
# rename column and overwrite values of the dataframe
df_exams = df_exams.rename(columns = {'Gender': 'gender'})
df_exams

,Student_ID,gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
0,1,Male,21,14,93,93,1,71,74,Pass,Bachelor's Degree
1,2,Female,21,21,94,69,1,95,79,Pass,Bachelor's Degree
2,3,Male,17,24,83,73,8,50,53,Pass,PhD
3,4,Male,19,28,52,99,4,59,74,Fail,PhD
4,5,Male,18,9,86,98,1,63,87,Pass,Bachelor's Degree
...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,PhD
496,497,Male,21,18,69,63,10,96,55,Pass,High School
497,498,Female,20,35,86,85,6,68,41,Fail,Master's Degree
498,499,Male,18,28,53,82,5,84,79,Fail,Associate Degree
499,500,Female,17,39,77,72,1,88,56,Pass,Associate Degree

In [22]:
# rename multiple columns and update the dataframe with inplace argument
df_exams.rename(columns = {
    'Age' : 'age',
    'Study_Hours_per_Week' : 'study_hours_per_week',
    'Attendance_Percentage' : 'attendance_percentage'
}, inplace = True)

In [23]:
# shoe dataframe
df_exams

,Student_ID,gender,age,study_hours_per_week,attendance_percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
0,1,Male,21,14,93,93,1,71,74,Pass,Bachelor's Degree
1,2,Female,21,21,94,69,1,95,79,Pass,Bachelor's Degree
2,3,Male,17,24,83,73,8,50,53,Pass,PhD
3,4,Male,19,28,52,99,4,59,74,Fail,PhD
4,5,Male,18,9,86,98,1,63,87,Pass,Bachelor's Degree
...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,PhD
496,497,Male,21,18,69,63,10,96,55,Pass,High School
497,498,Female,20,35,86,85,6,68,41,Fail,Master's Degree
498,499,Male,18,28,53,82,5,84,79,Fail,Associate Degree
499,500,Female,17,39,77,72,1,88,56,Pass,Associate Degree

# 2 Rename using Index argument

In [24]:
# rename index 0,1 and 2 and update the df
df_exams.rename(index={0:'A', 1:'B', 2:'C', 3:'D'}, inplace = True)

In [25]:
#show first four rows
df_exams.head(4)

,Student_ID,gender,age,study_hours_per_week,attendance_percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
A,1,Male,21,14,93,93,1,71,74,Pass,Bachelor's Degree
B,2,Female,21,21,94,69,1,95,79,Pass,Bachelor's Degree
C,3,Male,17,24,83,73,8,50,53,Pass,PhD
D,4,Male,19,28,52,99,4,59,74,Fail,PhD