In [1]:
import pandas as pd

In [4]:
# reading a csv file
df_exams = pd.read_csv("student_performance.csv")

In [7]:
#showing dataframe
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass
...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass
496,497,Male,21,18,69,63,10,96,55,Pass
497,498,Female,20,35,86,85,6,68,41,Fail
498,499,Male,18,28,53,82,5,84,79,Fail
499,500,Female,17,39,77,72,1,88,56,Pass

## Attributes

In [9]:
# getting access to the shape attribute
df_exams.shape

(500, 10)

In [11]:
# getting access to the index
df_exams.index

RangeIndex(start=0, stop=500, step=1)

In [13]:
# getting access to the columns
df_exams.columns

Index(['Student_ID', 'Gender', 'Age', 'Study_Hours_per_Week',
       'Attendance_Percentage', 'Previous_Grade', 'Assignments_Completed',
       'Midterm_Score', 'Final_Score', 'Overall_Result'],
      dtype='object')

In [14]:
# getting data types of each columns
df_exams.dtypes
#objects represent some kind of strings and int64 represent integers

Student_ID                int64
Gender                   object
Age                       int64
Study_Hours_per_Week      int64
Attendance_Percentage     int64
Previous_Grade            int64
Assignments_Completed     int64
Midterm_Score             int64
Final_Score               int64
Overall_Result           object
dtype: object

## Method

In [17]:
#showing first five columns
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass

In [19]:
#showing the info of the dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             500 non-null    int64
 1   Gender                 500 non-null    object
 2   Age                    500 non-null    int64
 3   Study_Hours_per_Week   500 non-null    int64
 4   Attendance_Percentage  500 non-null    int64
 5   Previous_Grade         500 non-null    int64
 6   Assignments_Completed  500 non-null    int64
 7   Midterm_Score          500 non-null    int64
 8   Final_Score            500 non-null    int64
 9   Overall_Result         500 non-null    object
dtypes: int64(8), object(2)
memory usage: 39.2+ KB

In [20]:
#describing basic statistics of the dataframe
df_exams.describe()

,Student_ID,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000
mean,250.500000,19.462000,22.140000,75.146000,74.708000,4.84800,69.356000,70.310000
std,144.481833,1.715354,10.133201,14.435423,14.872967,3.04885,17.420224,17.167392
min,1.000000,17.000000,5.000000,50.000000,50.000000,0.00000,40.000000,40.000000
25%,125.750000,18.000000,13.000000,62.000000,61.750000,2.00000,55.000000,56.000000
50%,250.500000,20.000000,23.000000,76.000000,74.500000,5.00000,68.000000,72.000000
75%,375.250000,21.000000,30.000000,87.250000,88.000000,7.25000,85.000000,85.000000
max,500.000000,22.000000,39.000000,100.000000,99.000000,10.00000,99.000000,99.000000

## Functions

In [24]:
# obtaining the length of the dataframe (number of rows)
len(df_exams)

500

In [29]:
# obtaining the highest index of the dataframe
print(max(df_exams)) #referes to columns
max(df_exams.index) #refers to row labels

Study_Hours_per_Week

499

In [32]:
# obtaining the lowest index of the dataframe
min(df_exams.index)

0

In [34]:
# obtaining the data type
type(df_exams)

pandas.core.frame.DataFrame

In [36]:
# rounding the values of the dataset
round(df_exams, 2) # first term refers to the dataframe and 2nd term refers decimal place
#as dataframe only have integers so it creates no differnece, but if contains float it will round up to 2 decimal places

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass
...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass
496,497,Male,21,18,69,63,10,96,55,Pass
497,498,Female,20,35,86,85,6,68,41,Fail
498,499,Male,18,28,53,82,5,84,79,Fail
499,500,Female,17,39,77,72,1,88,56,Pass