In [2]:
import pandas as pd

In [5]:
#reading csv file
df_exams = pd.read_csv('student_performance.csv')
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass

## 1 Selecting one Column

### 1.1 Syntax 1

In [10]:
# selecting column with [] (preferred way to select a column)
df_exams['Gender']

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
495      Male
496      Male
497    Female
498      Male
499    Female
Name: Gender, Length: 500, dtype: object

In [11]:
# check out the data type of a column
type(df_exams['Gender'])

pandas.core.series.Series

In [13]:
# series : attributes and methods
(df_exams['Gender']).index

RangeIndex(start=0, stop=500, step=1)

In [14]:
df_exams['Gender'].head()

0      Male
1    Female
2      Male
3      Male
4      Male
Name: Gender, dtype: object

### 1.2 Syntax 2

In [20]:
#select a column with .
df_exams.Student_ID

0        1
1        2
2        3
3        4
4        5
      ...
495    496
496    497
497    498
498    499
499    500
Name: Student_ID, Length: 500, dtype: int64

In [22]:
# select a column with . (pitfalls)
# if column name has space in it then it will cause error therefore [] is more preferred