In [46]:
import pandas as pd

In [47]:
# reading the csv file
df_exams = pd.read_csv('student_performance.csv')
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass

## 1 Adding a new column

### 1.1 adding a new column with a scalar value

In [48]:
# adding a new column to database
df_exams['Language_Score'] = 70
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score
0,1,Male,21,14,93,93,1,71,74,Pass,70
1,2,Female,21,21,94,69,1,95,79,Pass,70
2,3,Male,17,24,83,73,8,50,53,Pass,70
3,4,Male,19,28,52,99,4,59,74,Fail,70
4,5,Male,18,9,86,98,1,63,87,Pass,70
...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,70
496,497,Male,21,18,69,63,10,96,55,Pass,70
497,498,Female,20,35,86,85,6,68,41,Fail,70
498,499,Male,18,28,53,82,5,84,79,Fail,70
499,500,Female,17,39,77,72,1,88,56,Pass,70

### 1.2 Adding new column using Array

In [49]:
# create an array with elements same as the number of rows in dataframe
import numpy as np

In [50]:
# create Array of 500 rows using .arange(start, stop, increment)
l_score = np.arange(0,500,1)
l_score

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499])

In [51]:
# length of the Array
len(l_score)

500

In [52]:
# adding new column to dataframe using an array
df_exams['Language_score'] = l_score
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score,Language_score
0,1,Male,21,14,93,93,1,71,74,Pass,70,0
1,2,Female,21,21,94,69,1,95,79,Pass,70,1
2,3,Male,17,24,83,73,8,50,53,Pass,70,2
3,4,Male,19,28,52,99,4,59,74,Fail,70,3
4,5,Male,18,9,86,98,1,63,87,Pass,70,4
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,70,495
496,497,Male,21,18,69,63,10,96,55,Pass,70,496
497,498,Female,20,35,86,85,6,68,41,Fail,70,497
498,499,Male,18,28,53,82,5,84,79,Fail,70,498
499,500,Female,17,39,77,72,1,88,56,Pass,70,499

In [53]:
# create random integer numbers between 1 to 100
int_dialect_score = np.random.randint(1,100,size=500)
int_dialect_score

array([51, 91, 86, 49, 65, 48, 88, 48, 15, 44,  6, 43, 25, 57, 45, 36, 33,
       45, 34, 41, 72, 21, 31, 93, 52, 10, 23,  7, 89, 28, 88, 81,  5, 60,
       68, 97, 98, 13, 45, 39, 56, 69, 73, 79, 32, 94, 87, 25, 21, 26, 32,
       51, 66, 37, 22, 61, 51, 25, 49, 69, 58, 73, 24, 32, 31, 33,  6, 72,
       96, 67, 44, 89, 83,  8, 72, 48, 51, 97, 37, 30, 18, 97, 14, 82, 42,
       68, 35, 20, 76, 81,  1, 69, 74,  1, 90, 41,  9, 70, 13, 33, 31,  4,
       35, 40, 25,  4, 49, 88, 87, 71,  9,  2, 55, 35,  3, 94, 32, 16, 21,
       48, 93, 22, 92, 46,  5, 24, 85, 34, 26, 39,  7, 98, 76, 16, 48, 67,
       82, 14, 82, 33, 47, 64,  1, 49, 28, 50, 40, 93, 66, 57, 33, 48, 13,
       43, 94, 95, 49, 59, 24, 81, 91, 91, 95, 79, 31,  7,  9, 31, 86, 15,
       69, 25,  5, 53, 80, 37, 72, 48, 42, 93, 72, 52, 97,  4, 21, 12, 44,
       85, 39, 42,  4, 66, 63,  9, 94,  6, 91,  4, 48, 96, 17, 88, 66, 95,
       37, 54, 30, 20, 18, 96,  8, 29, 19, 24, 58, 59,  1, 99, 47,  1, 66,
        9,  7, 42, 33, 31, 89, 93, 42, 43, 94,  8, 91, 23,  3, 42, 19, 43,
       38, 61, 52,  8, 83, 57, 99, 69, 23, 17, 11, 34, 43, 19, 81, 46,  1,
        1, 77, 66, 64, 17, 91, 97, 71, 56, 51, 44, 12, 79, 52, 96, 16, 18,
       48, 71, 94,  9, 64, 98, 63, 45, 20, 45, 67,  9, 34, 84, 26, 40, 15,
       51, 59,  6, 43, 57, 23, 22, 13, 24, 35, 32, 28, 57, 64, 44, 55, 98,
       48, 18, 23, 13, 23, 33, 77, 84, 86,  5, 32, 27, 86, 94, 26, 75, 92,
       37, 27,  3, 34, 86, 72, 83, 78, 50, 28, 23, 19, 86, 68,  3, 92, 93,
       68, 83,  1, 93, 30, 32, 57, 32, 39, 49, 88, 92, 84, 44, 38, 90, 60,
       56, 15, 66, 25, 70, 71, 59, 20,  3, 51,  6, 77,  4, 36, 60, 46, 57,
       23, 83, 26, 52, 30, 94, 66, 40, 38,  4, 47, 46, 11, 58, 39, 86, 23,
       50, 19, 12, 36, 82, 45, 19,  2,  6, 23, 70, 23, 45, 38, 14, 73, 73,
        4, 55, 71, 31, 62, 48, 96, 46, 55, 95, 30, 47, 40, 92, 10, 14, 16,
       46, 92, 13, 83, 90, 96, 38, 46, 10, 43, 77, 73, 59, 75, 24, 60, 39,
       12, 19,  2, 17, 76, 34, 69, 55, 27, 54, 50, 41,  5, 32, 87, 34, 58,
       34,  3, 84, 38, 44, 20, 19, 44, 92, 55, 85,  9, 32,  9, 47, 23, 74,
       20, 12, 17,  8, 54, 35, 52, 70,  3, 27,  3, 68, 28, 69, 23, 48, 55,
       13, 68, 92, 43, 56, 50, 20])

In [54]:
# length of the array created
len(int_dialect_score)

500

In [55]:
# min value is inclusive and max value is exclusive
print(min(int_dialect_score))
print(max(int_dialect_score)) #Python int
max(int_dialect_score) #NumPy int

1
99

np.int64(99)

In [56]:
max(int_dialect_score).item()

99

In [57]:
# adding new column to the dataframe using Array
df_exams['Dialect_Score'] = int_dialect_score
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score,Language_score,Dialect_Score
0,1,Male,21,14,93,93,1,71,74,Pass,70,0,51
1,2,Female,21,21,94,69,1,95,79,Pass,70,1,91
2,3,Male,17,24,83,73,8,50,53,Pass,70,2,86
3,4,Male,19,28,52,99,4,59,74,Fail,70,3,49
4,5,Male,18,9,86,98,1,63,87,Pass,70,4,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,70,495,92
496,497,Male,21,18,69,63,10,96,55,Pass,70,496,43
497,498,Female,20,35,86,85,6,68,41,Fail,70,497,56
498,499,Male,18,28,53,82,5,84,79,Fail,70,498,50
499,500,Female,17,39,77,72,1,88,56,Pass,70,499,20

In [58]:
# create random float numbers from 1 to 100
np.random.uniform(1,100,size=500)

array([ 1.19623305, 20.74604042, 56.82560969, 84.4464973 , 79.32138862,
       36.9410094 , 93.9838664 ,  4.68298362, 83.45308514, 21.12658985,
       74.2201546 , 76.46069295, 98.79543134, 38.31356185, 85.2941366 ,
       76.50801116, 83.90252956, 48.19138964, 36.17087601, 33.83771998,
       74.98873292, 47.69102836, 67.90832553, 81.85645103,  8.95994353,
       58.08388685, 81.92332611,  6.92518152, 83.47657037, 53.10676573,
       24.45587132, 90.60191604, 40.97726301, 13.4969852 , 32.52081525,
       90.88864673, 36.02420954, 87.03792536, 98.65406765, 42.6520068 ,
       69.93775564, 85.37763054, 88.355934  , 25.98632792, 62.27760263,
       63.63373674, 85.22115735, 69.93885072, 59.92346703, 77.25630656,
       43.01610282, 96.72503271, 55.93977702, 86.69164759, 64.0635555 ,
       73.21283105, 84.20073731, 38.56922419, 22.81728647, 80.80047097,
       51.0346827 , 55.66445038, 46.5310483 , 56.29218251, 54.97388073,
       34.57761086,  3.9481966 , 71.19793671, 31.35250693, 22.15725267,
       22.39760073, 16.70876703, 13.43767602,  8.64788125, 82.03298105,
       12.84334378, 58.13172134, 10.8655743 ,  3.99152615, 81.89782199,
       30.22477458, 24.92019565, 91.46235837, 16.38081769, 66.70376732,
       97.44605803, 81.99889829, 86.91251548, 25.21841745, 54.52706291,
       36.64501295, 56.23362944, 59.41609768,  4.65686571, 56.25857587,
       46.38090547, 59.90554792, 55.11470127, 88.51054318, 49.42347287,
       21.17103847, 60.7296452 , 61.72213434, 79.52152197, 71.93300015,
       91.25922755, 48.98304289, 70.40295312, 98.82147014,  1.18404063,
       13.6079475 , 86.54414977, 86.88430521, 76.70065255, 47.48669477,
       34.9786275 , 64.32201548, 99.36821876,  7.05160617, 15.03131439,
       61.7687592 , 31.05044229, 13.32104604, 61.43061302,  6.06761457,
       30.68870367, 14.84416414, 57.61188724, 75.38056664, 30.15379938,
       46.59046941, 56.2298226 , 67.84391991, 13.8079267 , 96.96518091,
       18.74934731, 64.50778215, 14.14611083, 73.78468115, 14.59391274,
       52.35103192,  7.78419607, 63.64300955, 42.05739443, 49.73713075,
       88.00408772, 41.23055288, 25.97532789, 58.65257861,  4.02595594,
       36.29642611, 66.39753204, 55.28834214, 86.40664826,  9.82378055,
       61.87437761, 18.78657298, 23.18845197, 74.96525028, 20.28095969,
       35.39645638, 21.05935227, 16.57925756, 29.10652813, 29.20964593,
       59.265075  , 44.05781586, 64.52202071, 46.68338453, 38.68489082,
       51.71649807, 48.68356654, 98.7635858 , 35.37304251, 27.73800437,
       38.9099728 , 58.71328328, 82.72506204, 34.02557296, 78.58261069,
       78.67725192, 27.79407876, 21.6835658 , 61.45160538, 82.54037907,
       94.84287345, 43.45839137, 92.12582376,  1.1435455 , 68.11737703,
       77.58641537, 20.3072819 , 73.45010284, 95.40366692, 66.6625939 ,
        2.06785356, 51.56175585, 69.7742435 , 83.41999813, 25.67337903,
       70.78053547, 68.00153935, 75.11353788, 43.49207319, 96.77100157,
       30.68483614, 63.8839941 ,  4.79275705, 45.1226545 , 84.71397438,
       25.89666344, 31.808286  , 77.20420928, 69.09655305, 17.66451861,
        1.20743714, 70.24632145, 91.0279849 ,  9.27432635, 63.79158493,
       15.24555863, 89.04385442, 50.55676225, 15.9887574 , 81.45008501,
       49.17990098, 60.13146846, 31.27220509, 38.48010712, 87.46060944,
       67.32423313, 63.21149031, 87.77122651,  1.29894869, 38.91793523,
        5.66787578, 81.33840422, 51.33484828, 74.83017065, 53.76772565,
       97.89961185, 49.86963699, 69.67257888, 15.10456613, 16.76896322,
       13.2785792 , 30.05777699, 91.57494116, 57.98227645, 36.94787195,
       81.31778761, 63.01604744, 93.23433741, 26.44399672, 69.63058732,
       77.21810091, 87.25338739, 99.16303719, 49.41157833, 52.56504015,
       81.88197481, 26.85421641, 27.08288634, 60.17027103, 74.87304067,
       78.60882153,  7.10448951, 19.1294635 , 25.61723951, 38.02683684,
       18.2436909 , 46.61482619, 38.24874065, 38.96553509, 50.56452945,
       83.54377372, 44.37305697, 73.56572676, 13.92091182, 77.04964508,
       97.55529207, 54.24990607, 18.93691323, 34.81926974, 46.28709618,
       84.6391961 , 15.16674456, 96.58603655, 52.54682974, 67.23321703,
       77.11628228,  6.30791151, 15.22051959, 34.82740707,  8.73708123,
       74.95156166, 89.50632288, 38.99552066, 66.20681004, 39.81361381,
       80.94306813, 19.30323366, 71.58559915, 19.06923624, 49.76466604,
       80.6170893 , 43.11769517, 94.41005284, 53.17017822,  7.51868079,
       25.95627805, 79.99224144, 16.05422325,  5.19226817, 57.76639911,
       66.76694703, 79.1262504 , 98.83339436, 77.5758755 , 71.862374  ,
       75.89902268, 75.08817268, 87.69762131, 63.18448421,  3.41374902,
       41.92715892, 46.09632505, 87.57077725, 24.19761803, 70.72556248,
       67.53056347, 88.94641471,  8.93027463, 27.10496301, 35.05841301,
        7.09477773, 35.0080084 , 56.7151909 , 55.29105761, 41.38538619,
       81.28573078, 41.01168215, 51.35670012, 73.72147465, 47.07281639,
       17.79579887, 32.35526893, 56.28292597, 61.49959297, 39.56447934,
       74.29682919, 76.36394323, 36.92652724, 98.23119924, 97.84957617,
        4.94010447, 41.17470293, 98.18516922,  8.24639488, 88.08105223,
       49.77752717, 49.54415909, 83.44370873, 76.02380615, 81.75040384,
       93.19978582, 88.3508211 , 94.66623144, 68.33966324, 68.02596593,
       47.19054946, 55.37367639,  1.25338402, 72.90697048, 15.55440189,
       72.91328598, 24.6217156 , 17.62464398, 39.61332463, 30.33015251,
       19.80587403, 13.47867842, 97.23178214, 51.94279386, 61.97283819,
       77.20101546, 73.95651338, 85.66717524, 63.77653765, 44.78285047,
       86.03384326, 80.36634046, 39.12740477,  7.68823319, 91.72533133,
       80.0177633 , 72.04843199, 67.26735016, 77.47426868, 63.37984255,
       77.94571056, 76.54094823, 88.00734472, 88.83071621,  3.25835931,
       96.8202258 ,  3.79799698, 87.18044719, 27.62525265, 93.61144825,
       79.101083  , 42.75306501, 77.21916633, 61.61076771, 98.34865286,
       84.24753376, 54.40414198, 91.66553795, 67.71438885, 35.18158367,
       95.45918534, 90.2147703 , 18.89649155, 80.29041049, 86.68237514,
       95.05795363, 18.43554992, 58.92910597, 55.43559834, 67.2652409 ,
       99.64386544, 80.09903192, 67.5097299 , 94.34899777, 37.51065515,
        5.67816344, 90.62588749,  8.93529757, 52.3448589 ,  3.11946734,
       78.49950688, 32.48329825, 53.76323838, 98.74593116, 54.33013446,
       49.58009636, 61.40110137, 97.82918688, 91.39100901, 11.7741193 ,
       71.86225656,  7.54120691, 93.35912839, 55.21850295,  3.08993887,
       86.75765256, 15.50515171, 94.20106136, 83.07934598, 84.34641156,
       57.71943092, 27.47608   , 63.01950916, 70.202417  , 28.7199216 ,
       80.85184298, 57.15592375, 64.03934659, 48.58077148, 11.26591481,
       33.45849871, 38.39899854, 50.61297967, 51.3904    , 79.76154441,
       19.38503111, 58.67088184, 22.6756712 , 80.87483311, 96.16452263,
        7.41147743, 15.35501392, 90.35107482, 71.63833351, 95.06383813,
       91.67059956,  5.36081872, 87.61307221, 87.18416088, 78.08641175,
       83.44802832, 49.34296198, 65.7707882 , 32.58097947, 41.32305422,
       41.36049238, 93.43084097, 75.8225531 , 37.2199575 , 83.43670694])

### 1.3 using assign() method

In [67]:
# create random numbers for new score column
score1 = np.random.randint(1,100, size = 500)
score2 = np.random.randint(1,100, size = 500)

In [70]:
# create series using random integers
series1 = pd.Series(score1, index=np.arange(0,500,1))
series2 = pd.Series(score2, index=np.arange(0,500,1))

In [84]:
# using assign() method to add multiple columns
df_exams = df_exams.assign(Score_1 = series1, Score_2 = series2)
# assign() creates copy of the dataframe, to update we need to overwrite the dataframe which is done in the above statemtent

In [85]:
# show dataframe
df_exams

,Student_ID,Gender,Age,Test,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score,Language_score,Dialect_Score,Score_1,Score_2
0,1,Male,21,20,14,93,93,1,71,74,Pass,70,0,51,20,21
1,2,Female,21,99,21,94,69,1,95,79,Pass,70,1,91,99,86
2,3,Male,17,80,24,83,73,8,50,53,Pass,70,2,86,80,15
3,4,Male,19,18,28,52,99,4,59,74,Fail,70,3,49,18,59
4,5,Male,18,40,9,86,98,1,63,87,Pass,70,4,65,40,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,67,21,73,83,0,40,77,Pass,70,495,92,67,92
496,497,Male,21,83,18,69,63,10,96,55,Pass,70,496,43,83,50
497,498,Female,20,26,35,86,85,6,68,41,Fail,70,497,56,26,23
498,499,Male,18,35,28,53,82,5,84,79,Fail,70,498,50,35,50
499,500,Female,17,57,39,77,72,1,88,56,Pass,70,499,20,57,48

### using insert() method

In [83]:
# using index() method to add column in specific location
# index() doesn't create copy, it updates the values (not like assign())
df_exams.insert(3, 'Test', series1)

ValueError: cannot insert Test, already exists

In [86]:
#show dataframe
df_exams

,Student_ID,Gender,Age,Test,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score,Language_score,Dialect_Score,Score_1,Score_2
0,1,Male,21,20,14,93,93,1,71,74,Pass,70,0,51,20,21
1,2,Female,21,99,21,94,69,1,95,79,Pass,70,1,91,99,86
2,3,Male,17,80,24,83,73,8,50,53,Pass,70,2,86,80,15
3,4,Male,19,18,28,52,99,4,59,74,Fail,70,3,49,18,59
4,5,Male,18,40,9,86,98,1,63,87,Pass,70,4,65,40,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,67,21,73,83,0,40,77,Pass,70,495,92,67,92
496,497,Male,21,83,18,69,63,10,96,55,Pass,70,496,43,83,50
497,498,Female,20,26,35,86,85,6,68,41,Fail,70,497,56,26,23
498,499,Male,18,35,28,53,82,5,84,79,Fail,70,498,50,35,50
499,500,Female,17,57,39,77,72,1,88,56,Pass,70,499,20,57,48