In [1]:
import pandas as pd

In [3]:
# reading a csv file
df_exams = pd.read_csv('student_performance.csv')
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
0,1,Male,21,14,93,93,1,71,74,Pass,Bachelor's Degree
1,2,Female,21,21,94,69,1,95,79,Pass,Bachelor's Degree
2,3,Male,17,24,83,73,8,50,53,Pass,PhD
3,4,Male,19,28,52,99,4,59,74,Fail,PhD
4,5,Male,18,9,86,98,1,63,87,Pass,Bachelor's Degree

# 1 Sort a dataframe

In [5]:
# sort by one column
df_exams.sort_values(by='Midterm_Score') # can exclude by keyword

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
478,479,Male,22,27,86,69,9,40,43,Fail,Master's Degree
59,60,Male,19,30,67,61,5,40,51,Pass,High School
434,435,Female,18,39,90,57,0,40,51,Pass,Master's Degree
171,172,Male,21,25,62,53,9,40,67,Pass,Master's Degree
495,496,Male,21,21,73,83,0,40,77,Pass,PhD
...,...,...,...,...,...,...,...,...,...,...,...
154,155,Male,20,35,97,75,7,99,82,Pass,Associate Degree
314,315,Male,20,5,50,93,0,99,73,Fail,Master's Degree
288,289,Male,17,21,64,83,5,99,98,Pass,PhD
176,177,Male,21,8,68,65,10,99,79,Pass,Bachelor's Degree
493,494,Female,19,39,70,61,3,99,58,Pass,High School

In [7]:
# sort descending by one column
df_exams.sort_values('Midterm_Score', ascending=False)

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
204,205,Female,21,31,80,55,3,97,99,Pass,High School
165,166,Male,19,33,100,98,7,89,99,Pass,High School
258,259,Female,22,5,99,97,10,86,99,Pass,High School
265,266,Female,18,39,61,97,4,61,99,Pass,High School
466,467,Female,19,29,85,65,3,61,99,Pass,Master's Degree
...,...,...,...,...,...,...,...,...,...,...,...
455,456,Male,22,20,60,54,6,77,40,Fail,Associate Degree
308,309,Female,21,5,86,75,8,75,40,Fail,Associate Degree
198,199,Male,17,33,91,83,2,69,40,Fail,Master's Degree
137,138,Male,21,14,58,65,4,63,40,Fail,Bachelor's Degree
197,198,Female,20,19,72,53,0,60,40,Fail,PhD

In [10]:
# sort descending by multiple columns
df_exams.sort_values(['Final_Score', 'Midterm_Score'], ascending=False)

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
204,205,Female,21,31,80,55,3,97,99,Pass,High School
165,166,Male,19,33,100,98,7,89,99,Pass,High School
258,259,Female,22,5,99,97,10,86,99,Pass,High School
265,266,Female,18,39,61,97,4,61,99,Pass,High School
466,467,Female,19,29,85,65,3,61,99,Pass,Master's Degree
...,...,...,...,...,...,...,...,...,...,...,...
455,456,Male,22,20,60,54,6,77,40,Fail,Associate Degree
308,309,Female,21,5,86,75,8,75,40,Fail,Associate Degree
198,199,Male,17,33,91,83,2,69,40,Fail,Master's Degree
137,138,Male,21,14,58,65,4,63,40,Fail,Bachelor's Degree
197,198,Female,20,19,72,53,0,60,40,Fail,PhD

In [13]:
# sort descending by multiple columns and update dataframe
df_exams.sort_values(['Final_Score', 'Midterm_Score'], ascending=False, inplace=True)
df_exams #checks final score first, if matches then considers mideterm score

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
204,205,Female,21,31,80,55,3,97,99,Pass,High School
165,166,Male,19,33,100,98,7,89,99,Pass,High School
258,259,Female,22,5,99,97,10,86,99,Pass,High School
265,266,Female,18,39,61,97,4,61,99,Pass,High School
466,467,Female,19,29,85,65,3,61,99,Pass,Master's Degree
...,...,...,...,...,...,...,...,...,...,...,...
455,456,Male,22,20,60,54,6,77,40,Fail,Associate Degree
308,309,Female,21,5,86,75,8,75,40,Fail,Associate Degree
198,199,Male,17,33,91,83,2,69,40,Fail,Master's Degree
137,138,Male,21,14,58,65,4,63,40,Fail,Bachelor's Degree
197,198,Female,20,19,72,53,0,60,40,Fail,PhD

In [15]:
# sort descending with a key function
df_exams.sort_values('Parental_Level_of_Education', ascending = True, key = lambda col: col.str.lower())

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
411,412,Female,22,38,71,85,8,51,58,Pass,Associate Degree
310,311,Female,18,6,55,79,7,56,63,Fail,Associate Degree
120,121,Female,22,9,74,73,1,74,59,Pass,Associate Degree
245,246,Female,19,12,85,70,1,65,81,Pass,Associate Degree
431,432,Female,21,37,88,70,0,73,81,Pass,Associate Degree
...,...,...,...,...,...,...,...,...,...,...,...
147,148,Male,21,21,57,87,6,86,62,Fail,PhD
175,176,Female,18,30,73,80,4,71,62,Pass,PhD
78,79,Male,18,8,73,69,2,79,86,Pass,PhD
416,417,Male,17,30,75,52,3,60,52,Pass,PhD
197,198,Female,20,19,72,53,0,60,40,Fail,PhD