In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# read csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace = True)
# select columns
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [ ]:
# show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
E. Velasco,Edwin Alexis Velasco Uzuriaga,27,1991-11-05,179,78,Colombia,América de Cali
F. Zampano,Francesco Zampano,25,1993-09-30,177,74,Italy,Frosinone
M. Montini,Mattia Montini,27,1992-02-28,179,75,Italy,Dinamo Bucureşti
S. Dursun,Salih Dursun,27,1991-07-12,188,79,Turkey,Antalyaspor
I. Bel Hassani,Iliass Bel Hassani,26,1992-09-16,175,72,Morocco,PEC Zwolle

# 1.copy()

## 1.1 deep = True
### copy doesnt get updated

In [ ]:
# deep = True by default (Modifications to the data or indices of the copy)
df_copy = df.copy()

In [ ]:
# update value in og dataframe
df.loc['Cristiano Ronaldo', 'height_cm'] = 190

In [ ]:
# copy vs og dataframe
df_copy # doesn't gets updated as it is independent of og df
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
E. Velasco,Edwin Alexis Velasco Uzuriaga,27,1991-11-05,179,78,Colombia,América de Cali
F. Zampano,Francesco Zampano,25,1993-09-30,177,74,Italy,Frosinone
M. Montini,Mattia Montini,27,1992-02-28,179,75,Italy,Dinamo Bucureşti
S. Dursun,Salih Dursun,27,1991-07-12,188,79,Turkey,Antalyaspor
I. Bel Hassani,Iliass Bel Hassani,26,1992-09-16,175,72,Morocco,PEC Zwolle

## 1.2 deep = False
### (both gets updated)

In [ ]:
# Deep = False (Any changes to data of the og will be reflected in the shallow copy and vice versa)
df_shallow_copy = df.copy(deep=False)

In [ ]:
# update value in og df
df.loc['L. Messi', 'height_cm'] = 175

In [ ]:
# shallow copy vs og df
df
df_shallow_copy # both gets updated as they are dependent

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
M. Braithwaite,Martin Braithwaite,28,1991-06-05,177,73,Denmark,CD Leganés
P. Bargfrede,Philipp Bargfrede,30,1989-03-03,174,71,Germany,SV Werder Bremen
M. Destro,Mattia Destro,28,1991-03-20,182,80,Italy,Bologna
H. Behrens,Hanno Behrens,29,1990-03-26,188,82,Germany,1. FC Nürnberg
X. Chavalerin,Xavier Chavalerin,28,1991-03-07,179,69,France,Stade de Reims

### 1.3 Simple Assignment
#### (same as Deep = False)

In [ ]:
# make a copy
df_new_copy = df

In [ ]:
# update value in og df
df.loc['Neymar Jr', 'height_cm'] = 182

In [ ]:
# copy vs og df
df
df_new_copy # both df gets updated as it is a shallow copy
# same as using copy method where deep = False

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,182,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
M. Braithwaite,Martin Braithwaite,28,1991-06-05,177,73,Denmark,CD Leganés
P. Bargfrede,Philipp Bargfrede,30,1989-03-03,174,71,Germany,SV Werder Bremen
M. Destro,Mattia Destro,28,1991-03-20,182,80,Italy,Bologna
H. Behrens,Hanno Behrens,29,1990-03-26,188,82,Germany,1. FC Nürnberg
X. Chavalerin,Xavier Chavalerin,28,1991-03-07,179,69,France,Stade de Reims