In [1]:
import pandas as pd

In [2]:
# reading a csv file
df_laptop = pd.read_csv("laptop_price.csv")

In [3]:
#show dataframe
df_laptop.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,MSI,Model_1,Ultrabook,14.8,2560x1600,AMD Ryzen 7 3.2GHz,32GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.67,717.65
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84

# 1.Create a column based on 1 conditions: np.where()

In [4]:
import numpy as np

In [5]:
# create an array based on price tiers
np.where(df_laptop["Price_euros"] > 2000, 'Expensive', 'Cheap')

array(['Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Expensive', 'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap',
       'Expensive', 'Cheap', 'Expensive', 'Expensive', 'Expensive',
       'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Expensive',
       'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Expensive', 'Cheap',
       'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Expensive', 'Cheap',
       'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap',
       'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap',
       'Expensive', 'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Expensive',
       'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Expensive', 'Cheap',
       'Expensive', 'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Expensive',
       'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Expensive',
       'Expensive', 'Expensive', 'Expensive', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Expensive', 'Cheap',
       'Expensive', 'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Expensive',
       'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Expensive',
       'Cheap', 'Expensive', 'Expensive', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Expensive',
       'Cheap', 'Cheap', 'Expensive', 'Expensive', 'Expensive',
       'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Expensive', 'Expensive', 'Cheap', 'Cheap', 'Expensive', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap',
       'Cheap', 'Expensive', 'Expensive', 'Expensive', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Expensive', 'Cheap',
       'Cheap', 'Cheap', 'Expensive', 'Expensive', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Expensive', 'Expensive', 'Cheap', 'Cheap', 'Expensive',
       'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Expensive', 'Cheap',
       'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Expensive', 'Cheap',
       'Cheap', 'Expensive', 'Cheap', 'Cheap', 'Expensive', 'Expensive',
       'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap'], dtype='<U9')

In [6]:
# set it to new column
df_laptop['price_tier'] = np.where(df_laptop["Price_euros"] > 2000, 'Expensive', 'Cheap')

In [8]:
#show first 5 rows
df_laptop.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
0,1,MSI,Model_1,Ultrabook,14.8,2560x1600,AMD Ryzen 7 3.2GHz,32GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.67,717.65,Cheap
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62,Cheap
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84,Expensive
3,4,HP,Model_4,2 in 1 Convertible,16.5,2256x1504,AMD Ryzen 5 2.1GHz,16GB,128GB SSD,Intel HD Graphics 6000,macOS,1.53,1353.78,Cheap
4,5,Samsung,Model_5,Gaming,15.5,2560x1600,Intel Core i7 2.8GHz,32GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 10,2.10,1990.95,Cheap

In [9]:
# count values in price_tier column
df_laptop.value_counts("price_tier")

Price_tier
Cheap        225
Expensive     75
Name: count, dtype: int64

# 1.1 Exercise

In [13]:
# create an array based on screen size(inches) (size > 15 inch)
np.where(df_laptop["Inches"] > 15, 'Big', 'Small')

array(['Small', 'Big', 'Big', 'Big', 'Big', 'Small', 'Small', 'Small',
       'Big', 'Big', 'Big', 'Small', 'Small', 'Big', 'Small', 'Big',
       'Small', 'Big', 'Big', 'Big', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Big', 'Small', 'Small', 'Big', 'Small', 'Small',
       'Big', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Big',
       'Small', 'Big', 'Big', 'Small', 'Small', 'Small', 'Big', 'Small',
       'Small', 'Small', 'Big', 'Big', 'Big', 'Big', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Big', 'Small', 'Small', 'Big', 'Small',
       'Big', 'Small', 'Small', 'Big', 'Small', 'Small', 'Big', 'Small',
       'Big', 'Big', 'Big', 'Small', 'Big', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Big', 'Big', 'Big', 'Small', 'Big',
       'Small', 'Small', 'Small', 'Big', 'Small', 'Small', 'Small', 'Big',
       'Big', 'Small', 'Big', 'Big', 'Big', 'Small', 'Small', 'Small',
       'Big', 'Small', 'Small', 'Big', 'Small', 'Big', 'Small', 'Big',
       'Small', 'Big', 'Small', 'Big', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Small', 'Small', 'Small', 'Big',
       'Small', 'Small', 'Big', 'Small', 'Small', 'Big', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Big', 'Small', 'Big', 'Big', 'Small',
       'Big', 'Big', 'Small', 'Big', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Big', 'Big', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Big', 'Small', 'Small', 'Big', 'Small', 'Small',
       'Big', 'Small', 'Big', 'Big', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Small', 'Big', 'Big', 'Small',
       'Small', 'Small', 'Small', 'Big', 'Small', 'Small', 'Big', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Big', 'Big', 'Big',
       'Small', 'Big', 'Small', 'Small', 'Big', 'Big', 'Small', 'Big',
       'Small', 'Big', 'Small', 'Small', 'Big', 'Big', 'Small', 'Small',
       'Big', 'Big', 'Big', 'Big', 'Small', 'Big', 'Big', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Big', 'Big', 'Big', 'Small',
       'Big', 'Big', 'Small', 'Small', 'Big', 'Small', 'Small', 'Small',
       'Big', 'Small', 'Small', 'Small', 'Small', 'Big', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Small', 'Big', 'Small', 'Small',
       'Big', 'Small', 'Small', 'Big', 'Small', 'Small', 'Big', 'Big',
       'Big', 'Small', 'Big', 'Small', 'Small', 'Big', 'Big', 'Big',
       'Small', 'Small', 'Big', 'Big', 'Big', 'Small', 'Big', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Big'], dtype='<U5')

In [14]:
# set it to new column
df_laptop['screen_size'] =np.where(df_laptop["Inches"] > 15, 'Big', 'Small')

In [15]:
# show first 5 rows
df_laptop.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,screen_size
0,1,MSI,Model_1,Ultrabook,14.8,2560x1600,AMD Ryzen 7 3.2GHz,32GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.67,717.65,Cheap,Small
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62,Cheap,Big
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84,Expensive,Big
3,4,HP,Model_4,2 in 1 Convertible,16.5,2256x1504,AMD Ryzen 5 2.1GHz,16GB,128GB SSD,Intel HD Graphics 6000,macOS,1.53,1353.78,Cheap,Big
4,5,Samsung,Model_5,Gaming,15.5,2560x1600,Intel Core i7 2.8GHz,32GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 10,2.10,1990.95,Cheap,Big

In [16]:
# count values in screen_size column
df_laptop.value_counts('screen_size')

screen_size
Small    187
Big      113
Name: count, dtype: int64