In [25]:
import pandas as pd
import numpy as np

In [26]:
# reading csv file
df_laptop = pd.read_csv('laptop_price.csv')

In [27]:
# show df
df_laptop.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,MSI,Model_1,Ultrabook,14.8,2560x1600,AMD Ryzen 7 3.2GHz,32GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.67,717.65
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84
3,4,HP,Model_4,2 in 1 Convertible,16.5,2256x1504,AMD Ryzen 5 2.1GHz,16GB,128GB SSD,Intel HD Graphics 6000,macOS,1.53,1353.78
4,5,Samsung,Model_5,Gaming,15.5,2560x1600,Intel Core i7 2.8GHz,32GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 10,2.10,1990.95

# 1.Filter dataframe based on 1 condition

In [28]:
# find Apple laptops
df_laptop["Company"] == "Apple"

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297     True
298    False
299    False
Name: Company, Length: 300, dtype: bool

In [29]:
# create an array based on price > 2000 euros
df_laptop["Price_euros"] > 2000

0      False
1      False
2       True
3      False
4      False
       ...
295    False
296    False
297     True
298    False
299    False
Name: Price_euros, Length: 300, dtype: bool

# 2.Filter dataframe based on multiple conditions

In [30]:
# find apple laptops that cost more than 2000 euros
(df_laptop["Company"] == "Apple") & (df_laptop["Price_euros"] > 2000)

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297     True
298    False
299    False
Length: 300, dtype: bool

## 2.1 &(and)

In [31]:
# filter dataframe based on multiple condition
df_laptop[(df_laptop["Company"] == "Apple") & (df_laptop["Price_euros"] > 2000)]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
45,46,Apple,Model_46,Business,13.1,1920x1080,AMD Ryzen 5 2.1GHz,4GB,512GB SSD,Nvidia GTX 1650,Windows 11,2.41,2106.24
178,179,Apple,Model_179,Notebook,13.4,1920x1080,Intel Core i3 2.0GHz,4GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 11,1.88,2173.05
188,189,Apple,Model_189,Notebook,12.9,2560x1600,AMD Ryzen 5 2.1GHz,32GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 11,1.21,2118.41
229,230,Apple,Model_230,Gaming,12.1,1440x900,Intel Core i7 2.8GHz,16GB,1TB HDD,Nvidia RTX 3050,Windows 11,2.07,2469.35
233,234,Apple,Model_234,Business,17.1,1920x1080,AMD Ryzen 5 2.1GHz,4GB,1TB HDD,Nvidia RTX 3050,No OS,2.23,2268.34
249,250,Apple,Model_250,Ultrabook,13.1,2560x1600,Intel Core i7 2.8GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.58,2293.94
293,294,Apple,Model_294,Business,12.9,1920x1080,Intel Core i3 2.0GHz,32GB,1TB HDD,Intel Iris Plus Graphics 640,macOS,2.16,2373.98
297,298,Apple,Model_298,Business,12.4,2256x1504,AMD Ryzen 7 3.2GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.26,2056.10

# 2.2 |(or)

In [32]:
# find apple or dell laptops
(df_laptop['Company'] == 'Apple') | (df_laptop['Company'] == 'Dell')

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297     True
298     True
299    False
Name: Company, Length: 300, dtype: bool

In [33]:
# filter dataframe based on multiple conditions
df_laptop[(df_laptop['Company'] == 'Apple') | (df_laptop['Company'] == 'Dell')].value_counts('Company')

Company
Apple    43
Dell     29
Name: count, dtype: int64

In [38]:
# find laptops from Apple or Dell that cost over 2000 Euros
((df_laptop['Company'] == 'Apple') | (df_laptop['Company'] == 'Dell')) & (df_laptop["Price_euros"]>2000)

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297     True
298    False
299    False
Length: 300, dtype: bool

In [40]:
# filter dataframe based on multiple conditions
df_laptop[((df_laptop['Company'] == 'Apple') | (df_laptop['Company'] == 'Dell')) & (df_laptop["Price_euros"]>2000)]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
45,46,Apple,Model_46,Business,13.1,1920x1080,AMD Ryzen 5 2.1GHz,4GB,512GB SSD,Nvidia GTX 1650,Windows 11,2.41,2106.24
48,49,Dell,Model_49,Business,14.7,2560x1600,Intel Core i5 2.3GHz,4GB,1TB SSD,Intel HD Graphics 620,macOS,1.76,2012.16
178,179,Apple,Model_179,Notebook,13.4,1920x1080,Intel Core i3 2.0GHz,4GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 11,1.88,2173.05
181,182,Dell,Model_182,Gaming,13.3,2256x1504,AMD Ryzen 7 3.2GHz,8GB,256GB SSD,Nvidia GTX 1650,No OS,1.40,2095.26
188,189,Apple,Model_189,Notebook,12.9,2560x1600,AMD Ryzen 5 2.1GHz,32GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 11,1.21,2118.41
196,197,Dell,Model_197,Gaming,16.6,2256x1504,Intel Core i3 2.0GHz,8GB,1TB HDD,Intel Iris Plus Graphics 640,No OS,2.04,2346.10
212,213,Dell,Model_213,Ultrabook,16.4,2560x1600,AMD Ryzen 5 2.1GHz,4GB,1TB SSD,Intel HD Graphics 620,No OS,2.46,2090.50
220,221,Dell,Model_221,Notebook,14.0,1920x1080,AMD Ryzen 5 2.1GHz,32GB,512GB SSD,Intel HD Graphics 6000,No OS,1.60,2475.70
223,224,Dell,Model_224,2 in 1 Convertible,16.9,1366x768,Intel Core i3 2.0GHz,4GB,1TB SSD,Intel HD Graphics 620,Windows 11,1.78,2056.52
229,230,Apple,Model_230,Gaming,12.1,1440x900,Intel Core i7 2.8GHz,16GB,1TB HDD,Nvidia RTX 3050,Windows 11,2.07,2469.35
233,234,Apple,Model_234,Business,17.1,1920x1080,AMD Ryzen 5 2.1GHz,4GB,1TB HDD,Nvidia RTX 3050,No OS,2.23,2268.34
249,250,Apple,Model_250,Ultrabook,13.1,2560x1600,Intel Core i7 2.8GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.58,2293.94
293,294,Apple,Model_294,Business,12.9,1920x1080,Intel Core i3 2.0GHz,32GB,1TB HDD,Intel Iris Plus Graphics 640,macOS,2.16,2373.98
297,298,Apple,Model_298,Business,12.4,2256x1504,AMD Ryzen 7 3.2GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.26,2056.10