In [3]:
import pandas as pd
import numpy as np

In [4]:
# reading a csv file
df_laptops = pd.read_csv('laptop_price.csv')

In [5]:
# showe dataframe
df_laptops.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,MSI,Model_1,Ultrabook,14.8,2560x1600,AMD Ryzen 7 3.2GHz,32GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.67,717.65
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84
3,4,HP,Model_4,2 in 1 Convertible,16.5,2256x1504,AMD Ryzen 5 2.1GHz,16GB,128GB SSD,Intel HD Graphics 6000,macOS,1.53,1353.78
4,5,Samsung,Model_5,Gaming,15.5,2560x1600,Intel Core i7 2.8GHz,32GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 10,2.10,1990.95

# 1.Create a Conditional Column for more than 2 choices: np.select()

In [6]:
# create an array based on multiple price tiers (+2 choices)

# create conditions and value variables
conditions = [
    df_laptops['Price_euros'] > 3000,
    (df_laptops['Price_euros'] > 2000) & (df_laptops['Price_euros'] <= 3000),
    (df_laptops['Price_euros'] > 800) & (df_laptops['Price_euros'] <= 2000),
    df_laptops['Price_euros'] <= 800
]
values = ['Too Expensive', 'Expensive', 'Affordable', 'Cheap']

In [8]:
# set it to new column
df_laptops['Price_tiers'] = np.select(conditions, values, default='Other')

In [10]:
# show dataframe
df_laptops

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tiers
0,1,MSI,Model_1,Ultrabook,14.8,2560x1600,AMD Ryzen 7 3.2GHz,32GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.67,717.65,Cheap
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62,Affordable
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84,Expensive
3,4,HP,Model_4,2 in 1 Convertible,16.5,2256x1504,AMD Ryzen 5 2.1GHz,16GB,128GB SSD,Intel HD Graphics 6000,macOS,1.53,1353.78,Affordable
4,5,Samsung,Model_5,Gaming,15.5,2560x1600,Intel Core i7 2.8GHz,32GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 10,2.10,1990.95,Affordable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,Acer,Model_296,Gaming,12.6,1366x768,Intel Core i7 2.8GHz,4GB,512GB SSD,Intel HD Graphics 6000,Windows 11,1.40,1315.42,Affordable
296,297,Microsoft,Model_297,2 in 1 Convertible,13.5,1920x1080,AMD Ryzen 7 3.2GHz,4GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.54,403.33,Cheap
297,298,Apple,Model_298,Business,12.4,2256x1504,AMD Ryzen 7 3.2GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.26,2056.10,Expensive
298,299,Dell,Model_299,Notebook,12.4,2256x1504,Intel Core i5 2.3GHz,8GB,128GB SSD,Nvidia GTX 1650,Windows 10,2.26,1322.80,Affordable
299,300,Asus,Model_300,2 in 1 Convertible,16.6,2560x1600,Intel Core i7 2.8GHz,32GB,512GB SSD,Intel HD Graphics 6000,Windows 11,2.16,1041.94,Affordable

In [13]:
# counting elements under Price_tiers
df_laptops['Price_tiers'].value_counts()

Price_tiers
Affordable    162
Expensive      75
Cheap          63
Name: count, dtype: int64

In [15]:
(df_laptops["Price_euros"] > 3000).value_counts()

Price_euros
False    300
Name: count, dtype: int64

# 2.Exercise

In [20]:
# create an array based on multiple screen size tiers (+2choices)
# Too big>16, big>14, small>12, too small<=12
# create condition and value variables
conditions = [
    df_laptops['Inches'] > 16,
    (df_laptops['Inches'] <= 16) & (df_laptops['Inches'] > 14),
    (df_laptops['Inches'] <= 14) & (df_laptops['Inches'] > 12),
    (df_laptops['Inches'] <= 12)
]

values = ['Too Big', 'Big', 'Small', "Too Small"]

In [22]:
# set it to a new column
df_laptops['Screen_size'] = np.select(conditions, values, default='Other')

In [24]:
# show dataframe
df_laptops

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tiers,Screen_size
0,1,MSI,Model_1,Ultrabook,14.8,2560x1600,AMD Ryzen 7 3.2GHz,32GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.67,717.65,Cheap,Big
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62,Affordable,Too Big
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84,Expensive,Too Big
3,4,HP,Model_4,2 in 1 Convertible,16.5,2256x1504,AMD Ryzen 5 2.1GHz,16GB,128GB SSD,Intel HD Graphics 6000,macOS,1.53,1353.78,Affordable,Too Big
4,5,Samsung,Model_5,Gaming,15.5,2560x1600,Intel Core i7 2.8GHz,32GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 10,2.10,1990.95,Affordable,Big
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,Acer,Model_296,Gaming,12.6,1366x768,Intel Core i7 2.8GHz,4GB,512GB SSD,Intel HD Graphics 6000,Windows 11,1.40,1315.42,Affordable,Small
296,297,Microsoft,Model_297,2 in 1 Convertible,13.5,1920x1080,AMD Ryzen 7 3.2GHz,4GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.54,403.33,Cheap,Small
297,298,Apple,Model_298,Business,12.4,2256x1504,AMD Ryzen 7 3.2GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.26,2056.10,Expensive,Small
298,299,Dell,Model_299,Notebook,12.4,2256x1504,Intel Core i5 2.3GHz,8GB,128GB SSD,Nvidia GTX 1650,Windows 10,2.26,1322.80,Affordable,Small
299,300,Asus,Model_300,2 in 1 Convertible,16.6,2560x1600,Intel Core i7 2.8GHz,32GB,512GB SSD,Intel HD Graphics 6000,Windows 11,2.16,1041.94,Affordable,Too Big

In [25]:
# count values inside "screen_size" columns
df_laptops.value_counts('Screen_size')

Screen_size
Small        112
Big           98
Too Big       68
Too Small     22
Name: count, dtype: int64