In [ ]:
import pandas as pd

# 1)Read a .csv from a url with Pandas

In [ ]:
# reading 1 csv file from website
df_premier25 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [ ]:
# show dataframe
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,E0,11/02/2026,19:30,Crystal Palace,Burnley,2,3,A,2,3,...,2.03,1.83,NaN,NaN,2.04,1.83,2.00,1.78,2.15,1.85
256,E0,11/02/2026,19:30,Man City,Fulham,3,0,H,3,0,...,2.03,1.78,NaN,NaN,2.05,1.87,1.97,1.77,2.11,1.87
257,E0,11/02/2026,19:30,Nott'm Forest,Wolves,0,0,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.92,1.91,1.86,2.04,1.93
258,E0,11/02/2026,20:15,Sunderland,Liverpool,0,1,A,0,0,...,1.88,1.98,NaN,NaN,1.88,1.98,1.84,1.93,1.94,2.03
259,E0,12/02/2026,20:00,Brentford,Arsenal,1,1,D,0,0,...,1.98,1.88,NaN,NaN,1.98,1.91,1.94,1.84,2.04,1.93

In [ ]:
# rename columns
df_premier25.rename(columns={
    'FTHG':'home_goals',
    'FTAG' : 'away_goals'
}, inplace = True)

In [ ]:
# show dataframe
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,E0,11/02/2026,19:30,Crystal Palace,Burnley,2,3,A,2,3,...,2.03,1.83,NaN,NaN,2.04,1.83,2.00,1.78,2.15,1.85
256,E0,11/02/2026,19:30,Man City,Fulham,3,0,H,3,0,...,2.03,1.78,NaN,NaN,2.05,1.87,1.97,1.77,2.11,1.87
257,E0,11/02/2026,19:30,Nott'm Forest,Wolves,0,0,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.92,1.91,1.86,2.04,1.93
258,E0,11/02/2026,20:15,Sunderland,Liverpool,0,1,A,0,0,...,1.88,1.98,NaN,NaN,1.88,1.98,1.84,1.93,1.94,2.03
259,E0,12/02/2026,20:00,Brentford,Arsenal,1,1,D,0,0,...,1.98,1.88,NaN,NaN,1.98,1.91,1.94,1.84,2.04,1.93

#  2)Read .csv from multiple URLs with Pandas


*   https://www.football-data.co.uk/mmz4281/2526/E0.csv
*   https://www.football-data.co.uk/mmz4281/2526/E1.csv

**Link: root+season+league**

In [ ]:
# link structure
"https://www.football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2526/E0.csv'

In [ ]:
# create a root variable
root = "https://www.football-data.co.uk/mmz4281/"

## 2.1 Multiple leagues


* https://www.football-data.co.uk/mmz4281/2526/E0.csv
* https://www.football-data.co.uk/mmz4281/2526/E1.csv
* https://www.football-data.co.uk/mmz4281/2526/E2.csv
* https://www.football-data.co.uk/mmz4281/2526/E3.csv
* https://www.football-data.co.uk/mmz4281/2526/EC.csv

In [ ]:
# creating a list of leagues
leagues = ['E0', 'E1', 'E2','E3','EC']
frames = []

#looping through leagues, read, multiple csv and append it into the list
for league in leagues:
  df = pd.read_csv(root + '2526' + '/' + league + '.csv')
  frames.append(df)

In [ ]:
# length of frames
len(frames)

5

In [ ]:
# show 1st, 2nd and 3rd Element
frames[0]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,E0,11/02/2026,19:30,Crystal Palace,Burnley,2,3,A,2,3,...,2.03,1.83,NaN,NaN,2.04,1.83,2.00,1.78,2.15,1.85
256,E0,11/02/2026,19:30,Man City,Fulham,3,0,H,3,0,...,2.03,1.78,NaN,NaN,2.05,1.87,1.97,1.77,2.11,1.87
257,E0,11/02/2026,19:30,Nott'm Forest,Wolves,0,0,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.92,1.91,1.86,2.04,1.93
258,E0,11/02/2026,20:15,Sunderland,Liverpool,0,1,A,0,0,...,1.88,1.98,NaN,NaN,1.88,1.98,1.84,1.93,1.94,2.03
259,E0,12/02/2026,20:00,Brentford,Arsenal,1,1,D,0,0,...,1.98,1.88,NaN,NaN,1.98,1.91,1.94,1.84,2.04,1.93

## 2.2 Multiple Seasons

In [ ]:
for seasons in range(15,25,1):
  print(str(seasons)+str(seasons+1))

In [ ]:
# creating a list of leagues and an empty list to store all dataframes
leagues = ['E0', 'E1', 'E2']
frames_s = []

# looping through all leagues from 1st loop and range of season through 2nd loop
for league in leagues:
  for season in range(15,25,1):
    df_s = pd.read_csv(root + str(season)+str(season+1) + "/" + league + ".csv")
    df_s.insert(1,'Season',season)
    frames_s.append(df_s)

In [ ]:
# total frames generated 3*10 = 30
len(frames_s)

30

In [ ]:
frames_s[29]

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,24,09/08/2024,20:00,Barnsley,Mansfield,1,2,A,1,...,2.03,1.83,2.02,1.87,2.05,2.00,1.95,1.85,2.06,1.93
1,E2,24,10/08/2024,17:30,Birmingham,Reading,1,1,D,0,...,1.80,2.05,1.81,2.10,1.83,2.10,1.80,2.01,1.82,2.16
2,E2,24,10/08/2024,17:30,Bristol Rvs,Northampton,1,0,H,0,...,1.98,1.88,1.98,1.91,1.98,1.92,1.93,1.86,2.02,1.97
3,E2,24,10/08/2024,17:30,Burton,Lincoln,2,3,A,2,...,1.80,2.05,1.82,2.08,1.88,2.09,1.80,2.01,1.88,2.11
4,E2,24,10/08/2024,17:30,Crawley Town,Blackpool,2,1,H,2,...,1.83,2.03,1.85,2.04,1.86,2.05,1.82,1.99,1.89,2.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,24,03/05/2025,15:00,Northampton,Wigan,1,1,D,1,...,2.05,1.80,2.09,1.78,2.11,1.80,2.03,1.78,2.13,1.84
548,E2,24,03/05/2025,15:00,Reading,Barnsley,2,4,A,0,...,1.85,2.00,1.79,2.07,1.85,2.12,1.79,2.03,1.87,2.11
549,E2,24,03/05/2025,15:00,Rotherham,Peterboro,2,1,H,1,...,1.93,1.93,1.93,1.92,2.00,1.95,1.91,1.89,1.98,2.00
550,E2,24,03/05/2025,15:00,Shrewsbury,Crawley Town,1,2,A,0,...,2.03,1.83,2.05,1.81,2.10,1.83,2.03,1.79,2.11,1.87
551,E2,24,03/05/2025,15:00,Wycombe,Stockport,1,3,A,1,...,1.85,2.00,1.87,1.99,1.87,2.15,1.80,2.04,1.88,2.11

# 3)Organize all the data in the Dictionary

In [38]:
# create a dictionary with original name of league as key
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1',
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [41]:
# get a dictionary element
dict_countries['Spanish La Liga']

'SP1'

In [48]:
for league in dict_countries:
  print(dict_countries[league])

SP1
SP2
D1
E0
E2
E3

In [71]:
#creating new dictionary whose keys stores all leagues and values have data from year 2015-2024(2nd for loop) all concatened in one df respectively
dict_data_history = {}

for league in dict_countries:
  frames_D = []
  for seasons in range(15,25,1):
    df_D = pd.read_csv(root + str(seasons) + str(seasons+1) + "/" + dict_countries[league] + ".csv")
    df_D.insert(1,'Season',seasons)
    frames_D.append(df_D)
  df_concat = pd.concat(frames_D)
  dict_data_history[league] = df_concat

In [74]:
dict_data_history['Spanish La Liga']

,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,1XBCH,1XBCD,1XBCA,BFECH,BFECD,BFECA,BFEC>2.5,BFEC<2.5,BFECAHH,BFECAHA
0,SP1,15,21/08/15,Malaga,Sevilla,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,15,22/08/15,Ath Madrid,Las Palmas,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,15,22/08/15,Espanol,Getafe,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,15,22/08/15,La Coruna,Sociedad,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,15,22/08/15,Vallecano,Valencia,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,24,24/05/2025,Getafe,Celta,1,2,A,1,1,...,4.85,3.88,1.77,5.30,3.9,1.79,2.08,1.89,1.95,2.03
376,SP1,24,24/05/2025,Vallecano,Mallorca,0,0,D,0,0,...,1.53,4.19,7.29,1.50,4.6,8.20,2.10,1.87,1.85,2.14
377,SP1,24,25/05/2025,Girona,Ath Madrid,0,4,A,0,0,...,3.48,3.57,2.16,3.50,3.7,2.24,1.60,2.64,2.04,1.94
378,SP1,24,25/05/2025,Villarreal,Sevilla,4,2,H,3,1,...,1.75,4.42,4.30,1.80,4.3,4.60,1.60,2.62,2.03,1.95
379,SP1,24,25/05/2025,Ath Bilbao,Barcelona,0,3,A,0,2,...,3.49,4.00,2.03,3.35,4.0,2.18,1.47,3.05,2.07,1.91