In [90]:
import pandas as pd

In [91]:
df_movies = pd.read_csv('IMDb movies.csv', engine='python', on_bad_lines = 'skip')
df_ratings = pd.read_csv('IMDb ratings.csv')

In [92]:
df_movies = df_movies[['imdb_title_id', 'title', 'year','genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

In [142]:
print(df_movies.shape)
df_ratings.shape

(89703, 5)

(26077, 3)

# 1 merge()

In [93]:
df1 = pd.DataFrame({
    'id' : ['A', 'B', 'C', 'D'],
    'age' : [30, 23, 25, 22]
})

df2 = pd.DataFrame({
    'id' : ['C', 'D', 'E', 'F'],
    'job' : ['Doctor', 'Statistician', 'Accountant', 'Developer']
})

In [94]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [95]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

## 1.1 Inner Join

In [96]:
df_inner_join = df1.merge(df2, on = 'id', how = 'inner')

In [97]:
# shape
print(df1.shape)
print(df2.shape)
df_inner_join.shape

(4, 2)
(4, 2)

(2, 3)

### 1.1.1 Excercise

In [98]:
print(df_movies.columns)
print(df_ratings.columns)
# common column is "imdb_title_id"

Index(['imdb_title_id', 'title', 'year', 'genre', 'country'], dtype='object')
Index(['imdb_title_id', 'total_votes', 'mean_vote'], dtype='object')

In [99]:
# merge df_movies and df_ratings (inner join)
df_movies.merge(df_ratings, on = 'imdb_title_id', how = 'inner')
pd.merge(df_movies, df_ratings, on = 'imdb_title_id')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
29920,tt0102365,Mo deng ru lai shen zhang,1990,"Action, Comedy, Fantasy",Hong Kong,253,5.8
29921,tt0102367,Ma vie est un enfer,1991,"Comedy, Romance, Fantasy",France,763,5.8
29922,tt0102368,Madame Bovary,1991,"Drama, Romance",France,3451,6.6
29923,tt0102369,Madar,1990,Drama,Iran,3987,8.6
29924,tt0102371,The Magic Riddle,1991,"Animation, Fantasy",Australia,214,6.9

## 1.2 Outer Join

In [100]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [101]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

In [102]:
df1.merge(df2, on = 'id', how = 'outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [103]:
# shape
df1.merge(df2, on = 'id', how = 'outer').shape

(6, 3)

### 1.2.1 Exercise

In [104]:
print(df_movies.columns)
print(df_ratings.columns)
# common column is "imdb_title_id"

Index(['imdb_title_id', 'title', 'year', 'genre', 'country'], dtype='object')
Index(['imdb_title_id', 'total_votes', 'mean_vote'], dtype='object')

In [105]:
# merge df_movies and df_ratings (outerjoin)
df_outer_join = df_movies.merge(df_ratings, on = 'imdb_title_id', how = 'outer')
df_outer_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154.0,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589.0,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188.0,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446.0,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237.0,6.9
...,...,...,...,...,...,...,...
89698,tt9908390,Le lion,2020,Comedy,"France, Belgium",NaN,NaN
89699,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,NaN,NaN
89700,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,NaN,NaN
89701,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,NaN,NaN
89702,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,NaN,NaN

In [106]:
# shape
df_outer_join.shape

(89703, 7)

## 1.3 Exclusive Outer Join (Full Join)

In [107]:
# create full join
df1.merge(df2, on='id', how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [108]:
# indicator = True, exclusive full join
df1.merge(df2, on='id', how='outer', indicator = True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [109]:
# query, removing 'both'
merged  = df1.merge(df2, on='id', how='outer', indicator = True).query("_merge != 'both'")
merged

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

In [110]:
# shape
merged.shape

(4, 4)

### 1.3.1 Exercise

In [111]:
print(df_movies.columns)
df_ratings.columns
# imdb_title_id common column

Index(['imdb_title_id', 'title', 'year', 'genre', 'country'], dtype='object')

Index(['imdb_title_id', 'total_votes', 'mean_vote'], dtype='object')

In [112]:
# merge df_movies and df_ratings
df_movies.merge(df_ratings, on = 'imdb_title_id', how = 'outer')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154.0,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589.0,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188.0,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446.0,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237.0,6.9
...,...,...,...,...,...,...,...
89698,tt9908390,Le lion,2020,Comedy,"France, Belgium",NaN,NaN
89699,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,NaN,NaN
89700,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,NaN,NaN
89701,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,NaN,NaN
89702,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,NaN,NaN

In [113]:
# exclusive outer join, indicator = True
df_exclusive_full_join = df_movies.merge(df_ratings, on = 'imdb_title_id', how = 'outer', indicator = True)
df_exclusive_full_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,Miss Jerry,1894,Romance,USA,154.0,5.9,both
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589.0,6.3,both
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188.0,6.0,both
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446.0,5.3,both
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237.0,6.9,both
...,...,...,...,...,...,...,...,...
89698,tt9908390,Le lion,2020,Comedy,"France, Belgium",NaN,NaN,left_only
89699,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,NaN,NaN,left_only
89700,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,NaN,NaN,left_only
89701,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,NaN,NaN,left_only
89702,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,NaN,NaN,left_only

In [114]:
# remove 'both' with reference to _merge column using query
df_exclusive_full_join.query("_merge != 'both'")

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
29925,tt0102383,Malina,1991,"Drama, Fantasy, Mystery","Germany, Austria",NaN,NaN,left_only
29926,tt0102386,Man hua wei long,1992,"Action, Comedy",Hong Kong,NaN,NaN,left_only
29927,tt0102388,L'uomo della luna,1991,"Drama, Romance",USA,NaN,NaN,left_only
29928,tt0102394,L'uomo della porta accanto,1991,"Horror, Thriller",Germany,NaN,NaN,left_only
29929,tt0102395,Aiuto! Mi sono persa a New York,1991,"Comedy, Fantasy, Romance",USA,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...
89698,tt9908390,Le lion,2020,Comedy,"France, Belgium",NaN,NaN,left_only
89699,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,NaN,NaN,left_only
89700,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,NaN,NaN,left_only
89701,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,NaN,NaN,left_only
89702,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,NaN,NaN,left_only

## 1.4 Left Join

In [115]:
df1.merge(df2, on = 'id', how = 'left')

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        Doctor
3  D   22  Statistician

### 1.4.1 Exercise

In [116]:
# extract a 50% sample of the df_movies dataframe
df_movies_sample = df_movies.sample(frac = 0.5)
df_movies_sample

,imdb_title_id,title,year,genre,country
40198,tt0206550,Anazitisis...,1972,"Crime, Drama",Greece
45138,tt0305178,Massa'ot James Be'eretz Hakodesh,2003,"Comedy, Drama",Israel
64986,tt1712057,Vaanam,2011,"Action, Crime, Drama",India
56198,tt10081762,Breaking Surface,2020,"Action, Drama, Thriller","Sweden, Norway, Belgium"
88258,tt8549590,Chiwawa-chan,2019,"Drama, Mystery",Japan
...,...,...,...,...,...
62390,tt1480656,Cosmopolis,2012,"Crime, Drama, Fantasy","Canada, France, Portugal, Italy"
34286,tt0118766,Southie,1998,Drama,USA
8683,tt0037167,Passport to Destiny,1944,"Comedy, War",USA
45843,tt0322005,The Deviants,2004,"Comedy, Romance",USA
61049,tt1343103,Raptor Ranch,2013,"Action, Adventure, Comedy","Russia, USA"

In [117]:
# merge df_movies_sample and df_ratings (left join)
df_left = df_movies_sample.merge(df_ratings, on = 'imdb_title_id', how = 'left')
df_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0206550,Anazitisis...,1972,"Crime, Drama",Greece,NaN,NaN
1,tt0305178,Massa'ot James Be'eretz Hakodesh,2003,"Comedy, Drama",Israel,NaN,NaN
2,tt1712057,Vaanam,2011,"Action, Crime, Drama",India,NaN,NaN
3,tt10081762,Breaking Surface,2020,"Action, Drama, Thriller","Sweden, Norway, Belgium",NaN,NaN
4,tt8549590,Chiwawa-chan,2019,"Drama, Mystery",Japan,NaN,NaN
...,...,...,...,...,...,...,...
44847,tt1480656,Cosmopolis,2012,"Crime, Drama, Fantasy","Canada, France, Portugal, Italy",NaN,NaN
44848,tt0118766,Southie,1998,Drama,USA,NaN,NaN
44849,tt0037167,Passport to Destiny,1944,"Comedy, War",USA,214.0,6.4
44850,tt0322005,The Deviants,2004,"Comedy, Romance",USA,NaN,NaN
44851,tt1343103,Raptor Ranch,2013,"Action, Adventure, Comedy","Russia, USA",NaN,NaN

In [118]:
# shape
print(df_ratings.shape)
print(df_movies_sample.shape)
print(df_left.shape)

(26077, 3)
(44852, 5)
(44852, 7)

## 1.5 Exclusive Left Join
to create anytype of exclusive join, always start with how = 'outer'

In [119]:
# create outer join
df1.merge(df2, on = 'id', how = 'outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [120]:
# exclusive outer join, indicator = True
df1.merge(df2, on = 'id', how = 'outer', indicator = True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [121]:
# query to create exclusvie left join
df_exclusive_left = df1.merge(df2, on = 'id', how = 'outer', indicator = True).query("_merge == 'left_only'")
df_exclusive_left

  id   age  job     _merge
0  A  30.0  NaN  left_only
1  B  23.0  NaN  left_only

In [122]:
# shape
df_exclusive_left.shape

(2, 4)

### 1.5.1 Exercise

In [123]:
# make a copy of the df_movies dataframe
df_movie_2 = df_movies.copy()
df_movie_2

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
89698,tt9908390,Le lion,2020,Comedy,"France, Belgium"
89699,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
89700,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
89701,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
89702,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [124]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for index in df_movie_2.index:
  if index < 1000:
    df_movie_2.iloc[index, 0] = 'tt1234567890'

In [125]:
df_movie_2

,imdb_title_id,title,year,genre,country
0,tt1234567890,Miss Jerry,1894,Romance,USA
1,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt1234567890,Cleopatra,1912,"Drama, History",USA
4,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
89698,tt9908390,Le lion,2020,Comedy,"France, Belgium"
89699,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
89700,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
89701,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
89702,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [126]:
df_ratings.columns

Index(['imdb_title_id', 'total_votes', 'mean_vote'], dtype='object')

In [127]:
# merge df_movie_2 and df_ratings (exclusive left join)
df_movie_2.merge(df_ratings, on = 'imdb_title_id', how = 'outer', indicator = True)

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,NaN,NaN,NaN,NaN,154.0,5.9,right_only
1,tt0000574,NaN,NaN,NaN,NaN,589.0,6.3,right_only
2,tt0001892,NaN,NaN,NaN,NaN,188.0,6.0,right_only
3,tt0002101,NaN,NaN,NaN,NaN,446.0,5.3,right_only
4,tt0002130,NaN,NaN,NaN,NaN,2237.0,6.9,right_only
...,...,...,...,...,...,...,...,...
90698,tt9908390,Le lion,2020,Comedy,"France, Belgium",NaN,NaN,left_only
90699,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,NaN,NaN,left_only
90700,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,NaN,NaN,left_only
90701,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,NaN,NaN,left_only
90702,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,NaN,NaN,left_only

In [128]:
df_exclusive_left = df_movie_2.merge(df_ratings, on = 'imdb_title_id', how = 'outer', indicator = True).query("_merge == 'left_only'")
df_exclusive_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
29925,tt0102383,Malina,1991,"Drama, Fantasy, Mystery","Germany, Austria",NaN,NaN,left_only
29926,tt0102386,Man hua wei long,1992,"Action, Comedy",Hong Kong,NaN,NaN,left_only
29927,tt0102388,L'uomo della luna,1991,"Drama, Romance",USA,NaN,NaN,left_only
29928,tt0102394,L'uomo della porta accanto,1991,"Horror, Thriller",Germany,NaN,NaN,left_only
29929,tt0102395,Aiuto! Mi sono persa a New York,1991,"Comedy, Fantasy, Romance",USA,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...
90698,tt9908390,Le lion,2020,Comedy,"France, Belgium",NaN,NaN,left_only
90699,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,NaN,NaN,left_only
90700,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,NaN,NaN,left_only
90701,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,NaN,NaN,left_only
90702,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,NaN,NaN,left_only

In [129]:
# shape
print(df_exclusive_left.shape)
print(df_movie_2.shape)
print(df_ratings.shape)

# got 1000 because we created exclusve id above for first 1000 rows which we updated above

(60778, 8)
(89703, 5)
(26077, 3)

## 1.6 Right join

In [130]:
df1.merge(df2, on='id', how='right')

  id   age           job
0  C  25.0        Doctor
1  D  22.0  Statistician
2  E   NaN    Accountant
3  F   NaN     Developer

### 1.6.1 Exercise

In [131]:
# extract a 30% sample of the df_ratings dataframe
df_ratings_sample = df_ratings.sample(frac = 0.3)
df_ratings_sample

      imdb_title_id  total_votes  mean_vote
5670      tt0039815          280        6.1
19280     tt0080377        17116        6.2
393       tt0015493          200        6.4
17653     tt0075066        27349        7.4
450       tt0016377          112        7.0
...             ...          ...        ...
21337     tt0087034         1413        7.7
25146     tt0099235          428        4.8
14350     tt0065451         1382        6.4
23561     tt0094050          358        5.6
21459     tt0087461          145        5.4

[7823 rows x 3 columns]

In [132]:
# merge df_movies and df_ratings_sample (right join)
df_right = df_movies.merge(df_ratings_sample, on = 'imdb_title_id', how='right')
df_right

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0039815,Il mistero delle sette chiavi,1947,"Mystery, Thriller",USA,280,6.1
1,tt0080377,Fai come ti pare,1980,"Action, Comedy",USA,17116,6.2
2,tt0015493,L'ombra bianca,1924,Drama,UK,200,6.4
3,tt0075066,La pantera rosa sfida l'ispettore Clouseau,1976,"Comedy, Crime","UK, USA",27349,7.4
4,tt0016377,Soul-Fire,1925,Drama,USA,112,7.0
...,...,...,...,...,...,...,...
8964,tt0087034,Carmen,1984,"Drama, Music, Romance","France, Italy",1413,7.7
8965,tt0099235,The Cellar,1989,Horror,USA,428,4.8
8966,tt0065451,Barquero,1970,Western,USA,1382,6.4
8967,tt0094050,Extralunati,1987,Sci-Fi,USA,358,5.6
8968,tt0087461,Impatto mortale,1984,"Action, Crime, Drama",Italy,145,5.4

In [133]:
# shape
print(df_right.shape)
print(df_ratings_sample.shape)
print(df_movies.shape)

(8969, 7)
(7823, 3)
(89703, 5)

## 1.7 Exclusive Right Join

In [134]:
# creating exclusive outer join, indicator = True
df1.merge(df2, on='id', how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [135]:
# query to crate exclusive right join
df1.merge(df2, on='id', how='outer', indicator=True).query("_merge == 'right_only'")

  id  age         job      _merge
4  E  NaN  Accountant  right_only
5  F  NaN   Developer  right_only

### 1.7.1 Exercise

In [136]:
# make a copy of the df_ratings dataframe
df_ratings_2 = df_ratings.copy()

In [137]:
# set the first thousand values of 'imdb_title_id' columns as 'tt1234567890'
for index in df_ratings_2.index:
  if index < 1000:
    df_ratings_2.loc[index, 'imdb_title_id'] = 'tt1234567890'

In [138]:
# merge df_movies and df_ratings_2 (exclusive right)
df_movies.merge(df_ratings_2, on='imdb_title_id', how='outer', indicator = True)
df_exclusive_right = df_movies.merge(df_ratings_2, on='imdb_title_id', how='outer', indicator = True).query("_merge == 'right_only'")
df_exclusive_right.value_counts('_merge')

_merge
right_only    1000
left_only        0
both             0
Name: count, dtype: int64

In [139]:
# shape
print(df_ratings_2.shape)
print(df_exclusive_right.shape)
print(df_movies.shape)

(26077, 3)
(1000, 8)
(89703, 5)